FROM ghcr.io/mlflow/mlflow:v2.9.2

RUN pip install --no-cache-dir psycopg2-binary

EXPOSE 5000

CMD ["mlflow", "server", "--backend-store-uri", "postgresql://postgres:postgres@postgres-prod:5432/postgres", "--host", "0.0.0.0", "--port", "5000"]
